/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3badf99e35e6479e2b41615864feead9)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	SUPABASE_URL: "https://gcnbgdpicgeahxscpsfc.supabase.co";
	SUPABASE_PUBLISHABLE_KEY: "sb_publishable_Gf0t7yXfhyQbDBWG43YB3Q_71eKDwGb";
	VITE_SUPABASE_URL: string;
	VITE_SUPABASE_PUBLISHABLE_KEY: string;
	VITE_VAPID_PUBLIC_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
